# NVGIF C implementation
# Copyright (c) tiash-and-cats & contributors
# The NVGIF docs & reference implementations are licensed under the MIT License.
# In practice this means you can use this code in your projects without paying
# any kind of fee or subscription.

# tab char: (	)

CC=tcc
FLAGS=

all:
	$(CC) -o nvgifdecode.exe -I. main.c lodepng.c nvgif.c $(FLAGS)