[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nvgif"
version = "0.0.1"
authors = [
  { name="tiash-and-cats", email="tiash.rbm@gmail.com" },
]
description = "NVGIF reference implementation for Python"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "pillow==12.1.1",
]